#where to look for costmap parameters
costmap_parameter_source: "/local_costmap_node/costmap" #default "/local_costmap_node/costmap"

#frequency at which the get_footprint service should be called
footprint_update_frequency: 0.5


map_width: 5.0
map_height: 5.0
#Parameters specifying slow down behaviour
max_acceleration: [0.5, 0.5, 0.7]
costmap_resolution: 0.07

#Parameters specifying collision velocity filter 
influence_radius: 1.0 #[m] distance from robot_center
stop_threshold: 0.1 #[m]


